#!/usr/bin/env php
<?php
defined('APP_DIR') or define('APP_DIR',__DIR__.'/../app');

require_once  __DIR__.'/suda-console.php';

$options=getopt('', ['call:', 'database','db', 'router']);

// 设置目录
define('TOOL_DIR', SYS_DIR.'/tool');

if (isset($options['call'])) {
    array_shift($argv);
    $argv[1]=$options['call'];
    require_once TOOL_DIR.'/call.php';
} elseif (isset($options['database'])||isset($options['db'])) {
    require_once TOOL_DIR.'/db.php';
} elseif (isset($options['router'])) {
    require_once TOOL_DIR.'/router.php';
} else {
    echo 'Usage:'."\r\n";
    echo "\t".'--call name , call the functions'."\r\n";
    echo "\t".'--db option do database options'."\r\n";
    echo "\t".'--router name create router'."\r\n";
}
