#!/usr/bin/env php
<?php
defined('APP_DIR') or define('APP_DIR', __DIR__.'/../app');

require_once  __DIR__.'/suda-console.php';

$options=getopt('', ['call:', 'database', 'db', 'router', 'run', 'class:']);

// 设置目录
define('TOOL_DIR', SYS_DIR.'/tool');

if (isset($options['call'])) {
    array_shift($argv);
    $argv[1]=$options['call'];
    require_once TOOL_DIR.'/call.php';
} elseif (isset($options['database'])||isset($options['db'])) {
    require_once TOOL_DIR.'/db.php';
} elseif (isset($options['router'])) {
    require_once TOOL_DIR.'/router.php';
} elseif (isset($options['run'])) {
    require_once TOOL_DIR.'/run.php';
} elseif (isset($options['class'])) {
    require_once TOOL_DIR.'/class.php';
} else {
    echo 'Usage:'."\r\n";
    echo "\t".'--call name , call the functions'."\r\n";
    echo "\t".'--db option do database options'."\r\n";
    echo "\t".'--router name create router'."\r\n";
    echo "\t".'--class name create a class'."\r\n";
    echo "\t".'--run name#method run a class method'."\r\n";
}
