<?php
/* 爬虫特征用户代理信息 */
return [
    'TencentTraveler',
    'Baiduspider+',
    'BaiduGame',
    'Googlebot',
    'Baiduspider',
    'msnbot',
    'Sosospider+',
    'Sogou web spider',
    'ia_archiver',
    'Yahoo! Slurp',
    'YoudaoBot',
    'Yahoo Slurp',
    'MSNBot',
    'Java (Often spam bot)',
    'BaiDuSpider',
    'Voila',
    'Yandex bot',
    'BSpider',
    'twiceler',
    'Sogou Spider',
    'Speedy Spider',
    'Google AdSense',
    'Heritrix',
    'Python-urllib',
    'Alexa (IA Archiver)',
    'Ask',
    'Exabot',
    'Custo',
    'OutfoxBot/YodaoBot',
    'yacy',
    'SurveyBot',
    'legs',
    'lwp-trivial',
    'Nutch',
    'StackRambler',
    'The web archive (IA Archiver)',
    'Perl tool',
    'MJ12bot',
    'Netcraft',
    'MSIECrawler',
    'WGet tools',
    'larbin',
    'Fish search',
];