#!/usr/bin/env php
<?php
define('APP_DIR',__DIR__);

if (file_exists($path='__SYS_DIR__/suda-console.php')){
    require_once $path;
}else if (file_exists($path=__DIR__.'/../system/suda-console.php')) {
    require_once $path;
}
else {
    echo 'please flow this to start:'."\r\n";
    echo 'step 1 run command> git clone https://github.com/DXkite/suda.git '."\r\n";
    echo 'step 2> copy the system dir into '.dirname(__DIR__)."\r\n";
}


$options=getopt('', ['call:', 'database','db', 'router']);

// 设置目录
define('TOOL_DIR', SYS_DIR.'/tool');

if (isset($options['call'])) {
    array_shift($argv);
    $argv[1]=$options['call'];
    require_once TOOL_DIR.'/call.php';
} elseif (isset($options['database'])||isset($options['db'])) {
    require_once TOOL_DIR.'/db.php';
} elseif (isset($options['router'])) {
    require_once TOOL_DIR.'/router.php';
} else {
    echo 'Usage:'."\r\n";
    echo "\t".'--call name , call the functions'."\r\n";
    echo "\t".'--db option do database options'."\r\n";
    echo "\t".'--router name create router'."\r\n";
}
